buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$androidPluginVersion"
    }
}

allprojects {
    apply plugin: 'eclipse'
    apply plugin: 'idea'
}

configure(subprojects - project(':app')) {
    apply plugin: 'java-library'
    sourceCompatibility = JavaVersion.VERSION_1_8
    compileJava {
        options.incremental = true
    }
}

subprojects {
    version = '0.0.1-SNAPSHOT'
    ext.appName = 'GameName'
}

eclipse.project.name = 'GameName' + '-parent'
